# Numpy Arrays

In [1]:
my_list = [1,2,3]

In [2]:
my_list

[1, 2, 3]

In [3]:
import numpy as np

In [5]:
arr = np.array(my_list)

In [6]:
my_mat = [[1,2,3],[4,5,6],[7,8,9]]

In [7]:
my_mat

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [8]:
np.array(my_mat)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [10]:
np.arange(0,10,2) # third argument is the step size

array([0, 2, 4, 6, 8])

In [11]:
np.zeros(3)

array([0., 0., 0.])

In [13]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [14]:
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [16]:
np.linspace(0,10,10) # third argument is the number of values you want

array([ 0.        ,  1.11111111,  2.22222222,  3.33333333,  4.44444444,
        5.55555556,  6.66666667,  7.77777778,  8.88888889, 10.        ])

In [17]:
np.linspace(0,4,5)

array([0., 1., 2., 3., 4.])

In [18]:
np.linspace(0,10,5)

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [19]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [20]:
np.random.rand(5)

array([0.86061808, 0.49885886, 0.96602343, 0.66958826, 0.21179391])

In [22]:
np.random.rand(5,5) # uniform dist

array([[0.47689315, 0.41746975, 0.67334054, 0.91101453, 0.5990813 ],
       [0.90727022, 0.52392819, 0.45496184, 0.86223702, 0.67896279],
       [0.16794324, 0.53877972, 0.75198283, 0.56790145, 0.261373  ],
       [0.25145064, 0.50642217, 0.15273494, 0.22613339, 0.11058544],
       [0.13211624, 0.73506343, 0.89732115, 0.33375656, 0.94849072]])

In [23]:
np.random.randn(2) # normal dist

array([ 1.03803671, -0.31124554])

In [25]:
np.random.randn(4,4)

array([[ 0.00836466,  1.61887229, -0.65783091,  1.06190902],
       [-0.00781405, -0.52915039, -1.26437287,  0.64433398],
       [ 0.36327061,  2.37348033, -1.93051805,  1.0482376 ],
       [-1.39571089, -0.95480949, -0.48321691,  0.54579682]])

In [26]:
np.random.randint(1,100) # second argument is not included

40

In [27]:
np.random.randint(1,100,10)

array([27, 45, 40, 37, 45, 32, 52, 61, 75, 77])

In [28]:
arr = np.arange(25)

In [29]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [30]:
ranarr = np.random.randint(0,50,10)

In [31]:
ranarr

array([ 1, 24, 15, 37, 30, 37, 24, 21, 45, 32])

In [32]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [35]:
ranarr

array([ 1, 24, 15, 37, 30, 37, 24, 21, 45, 32])

In [36]:
ranarr.max()

45

In [37]:
ranarr.min()

1

In [38]:
ranarr

array([ 1, 24, 15, 37, 30, 37, 24, 21, 45, 32])

In [39]:
ranarr.argmax()

8

In [40]:
ranarr.argmin()

0

In [41]:
arr.shape

(25,)

In [42]:
arr = arr.reshape(5,5)

In [43]:
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [44]:
arr.shape

(5, 5)

In [45]:
arr.dtype

dtype('int32')

In [46]:
from numpy.random import randint

In [47]:
randint(2,10)

9

# NumPy Indexing and Selection

In [50]:
arr = np.arange(0,11)

In [51]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [52]:
arr[8]

8

In [53]:
arr[1:5]

array([1, 2, 3, 4])

In [54]:
arr[0:5]

array([0, 1, 2, 3, 4])

In [55]:
arr[:6]

array([0, 1, 2, 3, 4, 5])

In [56]:
arr[5:]

array([ 5,  6,  7,  8,  9, 10])

In [57]:
arr[0:5] = 100

In [58]:
arr

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

In [59]:
arr = np.arange(0,11)

In [60]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [61]:
slice_of_arr = arr[0:6]

In [62]:
slice_of_arr

array([0, 1, 2, 3, 4, 5])

In [65]:
slice_of_arr[:]

array([0, 1, 2, 3, 4, 5])

In [66]:
slice_of_arr[:] = 99

In [67]:
arr

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [68]:
arr_copy = arr.copy()

In [69]:
arr

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [70]:
arr_copy

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [71]:
arr_copy[:] = 100

In [72]:
arr_copy

array([100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100])

In [73]:
arr

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [74]:
arr_2d = np.array([[5,10,15],[20,25,30],[35,40,45]])

In [75]:
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [76]:
arr_2d[0][0]

5

In [77]:
arr_2d[0]

array([ 5, 10, 15])

In [78]:
arr_2d[1][1]

25

In [79]:
arr_2d[2][1]

40

In [80]:
arr_2d[0][2]

15

In [81]:
arr_2d[2,1]

40

In [82]:
arr_2d[2,2]

45

In [83]:
arr_2d[1,:]

array([20, 25, 30])

In [84]:
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [85]:
arr_2d[0:2][1:3]

array([[20, 25, 30]])

In [86]:
arr_2d[0:2]

array([[ 5, 10, 15],
       [20, 25, 30]])

In [90]:
arr_2d[:2][1:]

array([[20, 25, 30]])

In [91]:
arr_2d[:2,1:]

array([[10, 15],
       [25, 30]])

In [93]:
arr_2d[1:,0]

array([20, 35])

In [94]:
arr_2d[2,1:]

array([40, 45])

In [95]:
arr = np.arange(1,11)

In [96]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [97]:
arr > 5

array([False, False, False, False, False,  True,  True,  True,  True,
        True])

In [98]:
bool_arr = arr > 5

In [99]:
bool_arr

array([False, False, False, False, False,  True,  True,  True,  True,
        True])

In [101]:
arr[bool_arr]

array([ 6,  7,  8,  9, 10])

In [103]:
arr[arr>5] # summed up

array([ 6,  7,  8,  9, 10])

In [104]:
arr[arr<3]

array([1, 2])

In [105]:
arr_2d = np.arange(50)

In [106]:
arr_2d.reshape(5,10)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [107]:
arr_2d[1:3,3:5]

IndexError: too many indices for array

In [108]:
arr_2d[1:3]

array([1, 2])

In [109]:
arr_2d

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

In [110]:
arr_2d = arr_2d.reshape(5,10)

In [111]:
arr_2d[1:3,3:5]

array([[13, 14],
       [23, 24]])

In [112]:
arr_2d[1:,2:5]

array([[12, 13, 14],
       [22, 23, 24],
       [32, 33, 34],
       [42, 43, 44]])

# Numpy Operations

In [113]:
import numpy as np

In [114]:
arr = np.arange(0,11)

In [115]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [116]:
arr + arr

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [117]:
sum(arr)

55

In [118]:
arr - arr

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [119]:
arr * arr

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100])

In [120]:
arr + 100

array([100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110])

In [121]:
arr * 100

array([   0,  100,  200,  300,  400,  500,  600,  700,  800,  900, 1000])

In [122]:
1/0

ZeroDivisionError: division by zero

In [123]:
arr / arr

C:\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in true_divide
  """Entry point for launching an IPython kernel.


array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [124]:
1 / arr

C:\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in true_divide
  """Entry point for launching an IPython kernel.


array([       inf, 1.        , 0.5       , 0.33333333, 0.25      ,
       0.2       , 0.16666667, 0.14285714, 0.125     , 0.11111111,
       0.1       ])

In [125]:
arr ** 2

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100], dtype=int32)

In [126]:
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ,
       3.16227766])

In [127]:
np.exp(arr)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03, 2.20264658e+04])

In [128]:
np.max(arr)

10

In [129]:
arr.max()

10

In [130]:
np.sin(arr)

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ,
       -0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849,
       -0.54402111])

In [131]:
np.log(arr)

C:\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in log
  """Entry point for launching an IPython kernel.


array([      -inf, 0.        , 0.69314718, 1.09861229, 1.38629436,
       1.60943791, 1.79175947, 1.94591015, 2.07944154, 2.19722458,
       2.30258509])