## Creating the dataset

In [179]:
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.feature_extraction.text import TfidfTransformer

corpus = [
    'I really really like dogs',
    'I really really hate dogs',
    'I like apples'
]

## Bag of Words with ngram_range = (1,1)

In [180]:
vectorizer = CountVectorizer()
X = vectorizer.fit_transform(corpus)
print(vectorizer.get_feature_names())
print(X.toarray())

['apples', 'dogs', 'hate', 'like', 'really']
[[0 1 0 1 2]
 [0 1 1 0 2]
 [1 0 0 1 0]]


## TFIDF

In [181]:
tfidf = TfidfTransformer()
X = tfidf.fit_transform(X)
[[np.round(float(i), 2) for i in nested] for nested in X.toarray()]

[[0.0, 0.41, 0.0, 0.41, 0.82],
 [0.0, 0.39, 0.51, 0.0, 0.77],
 [0.8, 0.0, 0.0, 0.61, 0.0]]

## Bag of Words with ngram_range = (2,2)

In [182]:
corpus

['I really really like dogs', 'I really really hate dogs', 'I like apples']

In [183]:
vectorizer2 = CountVectorizer(analyzer='word', ngram_range=(2, 2))
X2 = vectorizer2.fit_transform(corpus)
print(vectorizer2.get_feature_names())
print(X2.toarray())

['hate dogs', 'like apples', 'like dogs', 'really hate', 'really like', 'really really']
[[0 0 1 0 1 1]
 [1 0 0 1 0 1]
 [0 1 0 0 0 0]]


## TFIDF

In [184]:
tfidf = TfidfTransformer()
X = tfidf.fit_transform(X)
[[np.round(float(i), 2) for i in nested] for nested in X.toarray()]

[[0.0, 0.41, 0.0, 0.41, 0.82],
 [0.0, 0.35, 0.61, 0.0, 0.71],
 [0.87, 0.0, 0.0, 0.5, 0.0]]